import { createContext, useContext, useEffect, useState } from 'react';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut, createUserWithEmailAndPassword, GoogleAuthProvider, signInWithPopup, type User, updateEmail, updateProfile } from 'firebase/auth';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { auth, db, useFirebase } from '../lib/firebase';
export type Role = 'user' | 'admin';
export type Profile = { firstName: string; lastName: string; birthYear: number; telegram?: string; role: Role };
type ProfileUpdate = Omit<Profile, 'role'> & { email: string };
type Auth = { user: User | null; profile: Profile | null; isAdmin: boolean; loading: boolean; login: (email: string, password: string) => Promise<void>; register: (email: string, password: string, profile: Omit<Profile, 'role'>) => Promise<void>; loginWithGoogle: () => Promise<void>; updateAccount: (data: ProfileUpdate) => Promise<void>; logout: () => Promise<void>; };
const AuthContext = createContext<Auth | null>(null);
// UID администратора задаётся в .env.local. В Firestore Rules используйте тот же UID.
// Переменная окружения приоритетна. Fallback синхронизирован с bootstrapAdmin
// в firestore.rules, поэтому уже назначенный администратор не теряет доступ.
const adminUid = (import.meta.env.VITE_ADMIN_UID as string | undefined) || 'BBdM0CUz7jgSGGc0R6Oj1Q7rBBQ2';
const roleFor = (uid: string): Role => uid === adminUid ? 'admin' : 'user';
export function AuthProvider({ children }: { children: React.ReactNode }) { const [user, setUser] = useState<User | null>(null); const [profile, setProfile] = useState<Profile | null>(null); const [loading, setLoading] = useState(true); const makeProfile = (u: User): Profile => { const parts = (u.displayName || 'User').split(' '); return { firstName: parts[0], lastName: parts.slice(1).join(' '), birthYear: 0, telegram: '', role: roleFor(u.uid) }; }; const loadProfile = async (u: User) => { if (!db) return; const ref = doc(db, 'users', u.uid); const snapshot = await getDoc(ref); if (snapshot.exists()) { const saved = snapshot.data() as Partial<Profile>; const effectiveRole = roleFor(u.uid) === 'admin' ? 'admin' : saved.role || 'user'; const data: Profile = { firstName: saved.firstName || 'User', lastName: saved.lastName || '', birthYear: saved.birthYear || 0, telegram: saved.telegram || '', role: effectiveRole }; setProfile(data); if (effectiveRole === 'admin' && saved.role !== 'admin') void setDoc(ref, { role: 'admin' }, { merge: true }).catch(console.error); return; } const data = makeProfile(u); await setDoc(ref, data); setProfile(data); };
 useEffect(() => { if (!useFirebase || !auth) { setLoading(false); return; } return onAuthStateChanged(auth, async u => { setUser(u); setProfile(null); try { if (u) await loadProfile(u); } finally { setLoading(false); } }); }, []);
 const login = async (email: string, password: string) => { if (!auth) throw new Error('Firebase не настроен. Добавьте .env.local'); await signInWithEmailAndPassword(auth, email, password); }; const register = async (email: string, password: string, profileData: Omit<Profile, 'role'>) => { if (!auth || !db) throw new Error('Firebase не настроен. Добавьте .env.local'); const credential = await createUserWithEmailAndPassword(auth, email, password); const data: Profile = { ...profileData, role: roleFor(credential.user.uid) }; await updateProfile(credential.user, { displayName: `${data.firstName} ${data.lastName}`.trim() }); await setDoc(doc(db, 'users', credential.user.uid), data); setProfile(data); }; const loginWithGoogle = async () => { if (!auth) throw new Error('Firebase не настроен. Добавьте .env.local'); await signInWithPopup(auth, new GoogleAuthProvider()); };
 // Email хранит Firebase Auth, а остальные поля — Firestore. Роль сюда не передаётся,
 // поэтому пользователь не может изменить её через экран профиля.
 const updateAccount = async (data: ProfileUpdate) => { const activeUser = auth?.currentUser || user; if (!activeUser) throw new Error('Сначала войдите в аккаунт.'); const nextProfile: Profile = { firstName: data.firstName.trim(), lastName: data.lastName.trim(), birthYear: data.birthYear, telegram: data.telegram.trim().replace(/^@/, ''), role: profile?.role || roleFor(activeUser.uid) }; if (useFirebase && db) { if (data.email.trim() !== activeUser.email) await updateEmail(activeUser, data.email.trim()); await updateProfile(activeUser, { displayName: `${nextProfile.firstName} ${nextProfile.lastName}`.trim() }); await setDoc(doc(db, 'users', activeUser.uid), nextProfile, { merge: true }); } setUser(activeUser); setProfile(nextProfile); };
 return <AuthContext.Provider value={{ user, profile, isAdmin: profile?.role === 'admin', loading, login, register, loginWithGoogle, updateAccount, logout: async () => { if (auth) await signOut(auth); } }}>{children}</AuthContext.Provider>; }
export const useAuth = () => { const value = useContext(AuthContext); if (!value) throw new Error('AuthProvider is required'); return value; };
