import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CheckCheck, Eye, FileText, LogOut, Mail, MessageCircle, Plus, Trash2 } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { getArticles, getLessons, getMessages, markMessageRead, removeArticle, removeLesson, removeMessage } from '../../lib/contentService';
import type { Article, ContactMessage, Lesson } from '../../types';

export default function AdminPage() {
  const { logout } = useAuth(); const [lessons, setLessons] = useState<Lesson[]>([]); const [articles, setArticles] = useState<Article[]>([]); const [messages, setMessages] = useState<ContactMessage[]>([]); const [error, setError] = useState('');
  const load = () => { setError(''); Promise.all([getLessons(), getArticles(), getMessages()]).then(([a, b, c]) => { setLessons(a); setArticles(b); setMessages(c); }).catch(e => setError(e instanceof Error ? e.message : 'Не удалось загрузить админ-панель.')); };
  useEffect(load, []);
  const destroy = async (kind: 'lesson' | 'article', id: string) => { if (!confirm('Удалить без возможности восстановления?')) return; try { kind === 'lesson' ? await removeLesson(id) : await removeArticle(id); load(); } catch (e) { setError(e instanceof Error ? e.message : 'Удаление не удалось.'); } };
  const read = async (id: string) => { try { await markMessageRead(id); setMessages(x => x.map(m => m.id === id ? { ...m, read: true } : m)); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось отметить сообщение.'); } };
  const remove = async (id: string) => { if (!confirm('Удалить это сообщение?')) return; try { await removeMessage(id); setMessages(x => x.filter(m => m.id !== id)); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось удалить сообщение.'); } };
  return <section className="mx-auto max-w-6xl px-4 py-10"><div className="flex justify-between gap-4"><div><p className="font-bold text-brand-600">CMS · ADMIN</p><h1 className="text-3xl font-black">Админ-панель</h1></div><button onClick={logout} className="rounded-xl border p-3 dark:border-slate-700" title="Выйти"><LogOut size={17}/></button></div>{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-3"><Stat icon={<Eye/>} label="Уроков" value={lessons.length}/><Stat icon={<FileText/>} label="Статей" value={articles.length}/><Stat icon={<Mail/>} label="Новых обращений" value={messages.filter(x => !x.read).length}/></div><Content title="Уроки" href="/admin/lessons/new" label="Новый урок">{lessons.map(x => <Row key={x.id} text={`${x.title.ru} · ${x.level} · ${x.views} views`} edit={`/admin/lessons/${x.id}`} remove={() => destroy('lesson', x.id)}/>)}</Content><Content title="Статьи" href="/admin/articles/new" label="Новая статья">{articles.map(x => <Row key={x.id} text={x.title.ru} edit={`/admin/articles/${x.id}`} remove={() => destroy('article', x.id)}/>)}</Content><h2 className="mt-10 text-xl font-bold">Обращения</h2><div className="mt-4 grid gap-3">{messages.length ? messages.map(m => <article key={m.id} className={'flex items-start justify-between gap-4 rounded-xl border p-4 transition dark:border-slate-800 ' + (m.read ? 'opacity-50 grayscale' : 'border-brand-200 bg-white dark:bg-slate-900')}><div><div className="flex flex-wrap items-center gap-2"><b>{m.name}</b><span className="text-sm text-slate-500">{m.email}</span>{m.read && <span className="inline-flex items-center gap-1 text-xs text-green-600"><CheckCheck size={15}/>Прочитано</span>}</div><p className="mt-2">{m.message}</p></div><div className="flex shrink-0 gap-1">{m.userId && <Link to={`/admin/chats/${m.userId}`} onClick={() => !m.read && read(m.id)} title="Открыть чат" className="rounded-lg p-2 text-brand-600 hover:bg-brand-50"><MessageCircle size={18}/></Link>}{!m.read && <button onClick={() => read(m.id)} title="Отметить прочитанным" className="rounded-lg p-2 text-green-600 hover:bg-green-50"><CheckCheck size={18}/></button>}<button onClick={() => remove(m.id)} title="Удалить" className="rounded-lg p-2 text-rose-500 hover:bg-rose-50"><Trash2 size={18}/></button></div></article>) : <p className="text-slate-500">Пока нет сообщений.</p>}</div></section>;
}
function Content({ title, href, label, children }: { title: string; href: string; label: string; children: React.ReactNode }) { return <div className="mt-10"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><Link to={href} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2 font-bold text-white"><Plus size={17}/>{label}</Link></div><div className="rounded-2xl bg-white dark:bg-slate-900">{children}</div></div>; }
function Row({ text, edit, remove }: { text: string; edit: string; remove: () => void }) { return <div className="flex items-center justify-between gap-3 border-b p-4 last:border-0 dark:border-slate-800"><span className="font-medium">{text}</span><span className="shrink-0"><Link to={edit} className="mr-3 text-brand-600">Изменить</Link><button onClick={remove} className="text-rose-500">Удалить</button></span></div>; }
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-2xl bg-brand-50 p-5 dark:bg-slate-900"><span className="text-brand-600">{icon}</span><b className="mt-3 block text-2xl">{value}</b><span className="text-sm">{label}</span></div>; }
