import { useEffect, useState } from 'react';
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';
import { useNavigate, useParams } from 'react-router-dom';
import { getArticles, saveArticle, uploadImage } from '../../lib/contentService';
import { splitTags, tagsFor } from '../../lib/tags';
import type { Article } from '../../types';

const quillModules = { toolbar: [['bold', 'italic', 'underline', 'strike'], [{ header: [1, 2, 3, false] }], [{ size: ['small', false, 'large', 'huge'] }], [{ list: 'ordered' }, { list: 'bullet' }], [{ align: [] }], ['link', 'image'], ['clean']] };
const isUrl = (value: string) => !value || /^https?:\/\/.+/i.test(value.trim());

export default function ArticleFormPage() {
  const nav = useNavigate(); const { id } = useParams(); const [ru, setRu] = useState(''); const [uz, setUz] = useState(''); const [titleRu, setTitleRu] = useState(''); const [titleUz, setTitleUz] = useState(''); const [image, setImage] = useState(''); const [detailImage, setDetailImage] = useState(''); const [tagsRu, setTagsRu] = useState(''); const [tagsUz, setTagsUz] = useState(''); const [loading, setLoading] = useState(Boolean(id)); const [uploading, setUploading] = useState<'image' | 'detailImage' | ''>(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!id) return; getArticles().then(items => { const article = items.find(item => item.id === id); if (!article) { setError('Статья не найдена.'); return; } setTitleRu(article.title.ru); setTitleUz(article.title.uz); setRu(article.content.ru); setUz(article.content.uz); setImage(article.image); setDetailImage(article.detailImage || ''); setTagsRu(tagsFor(article.tags, 'ru').join(', ')); setTagsUz(tagsFor(article.tags, 'uz').join(', ')); }).catch(() => setError('Не удалось загрузить статью.')).finally(() => setLoading(false)); }, [id]);
  const upload = async (field: 'image' | 'detailImage', file?: File) => { if (!file) return; try { setUploading(field); setError(''); const url = await uploadImage(file, 'article-images'); field === 'image' ? setImage(url) : setDetailImage(url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось загрузить изображение.'); } finally { setUploading(''); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!titleRu.trim() || !titleUz.trim() || !ru.trim() || !uz.trim()) { setError('Заполните заголовок и текст статьи на обоих языках.'); return; } if (!image.trim()) { setError('Добавьте обложку: URL или загрузите файл.'); return; } if (!isUrl(image) || !isUrl(detailImage)) { setError('Проверьте ссылку на изображение.'); return; } setSaving(true); setError(''); try { const article: Article = { id: id || crypto.randomUUID(), title: { ru: titleRu.trim(), uz: titleUz.trim() }, excerpt: { ru: ru.replace(/<[^>]*>/g, '').slice(0, 160), uz: uz.replace(/<[^>]*>/g, '').slice(0, 160) }, content: { ru, uz }, image: image.trim(), ...(detailImage.trim() ? { detailImage: detailImage.trim() } : {}), tags: { ru: splitTags(tagsRu), uz: splitTags(tagsUz) }, createdAt: new Date().toISOString() }; await saveArticle(article); nav('/admin'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить статью.'); } finally { setSaving(false); } };
  if (loading) return <div className="p-10">Loading…</div>;
  return <section className="mx-auto max-w-3xl px-4 py-10"><h1 className="text-3xl font-black">{id ? 'Редактировать статью' : 'Новая статья'}</h1><p className="mt-2 text-sm text-slate-500">Загрузите обложку для карточки, а фотографию внутри статьи добавляйте по желанию.</p><form noValidate onSubmit={submit} className="mt-6 space-y-5 rounded-2xl bg-white p-6 shadow-soft dark:bg-slate-900"><TextInput label="Заголовок (RU)" value={titleRu} onChange={setTitleRu} /><TextInput label="Sarlavha (UZ)" value={titleUz} onChange={setTitleUz} /><ImageField label="Обложка для карточки" hint="URL или загрузка файла." value={image} onChange={setImage} field="image" uploading={uploading} onUpload={upload} /><ImageField label="Фото внутри статьи (необязательно)" hint="Полное изображение будет показано внутри статьи." value={detailImage} onChange={setDetailImage} field="detailImage" uploading={uploading} onUpload={upload} /><TextInput label="Теги (RU, через запятую)" value={tagsRu} onChange={setTagsRu} /><TextInput label="Teglar (UZ, vergul orqali)" value={tagsUz} onChange={setTagsUz} /><Editor label="Текст RU" value={ru} onChange={setRu} /><Editor label="Matn UZ" value={uz} onChange={setUz} />{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={Boolean(uploading) || saving} className="rounded-xl bg-brand-600 px-5 py-3 font-bold text-white disabled:opacity-60">{uploading ? 'Загрузка…' : saving ? 'Сохранение…' : 'Сохранить статью'}</button></form></section>;
}
function Editor({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div className="min-w-0"><p className="mb-1 font-bold">{label}</p><ReactQuill theme="snow" modules={quillModules} value={value} onChange={onChange} /></div>; }
function TextInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block min-w-0 text-sm font-semibold">{label}<input className="mt-1 min-w-0 w-full rounded-xl border bg-transparent p-3 break-all dark:border-slate-700" value={value} onChange={event => onChange(event.target.value)} /></label>; }
function ImageField({ label, hint, field, value, onChange, uploading, onUpload }: { label: string; hint: string; field: 'image' | 'detailImage'; value: string; onChange: (value: string) => void; uploading: string; onUpload: (field: 'image' | 'detailImage', file?: File) => void }) { return <div className="min-w-0 rounded-2xl border border-dashed border-slate-300 p-4 dark:border-slate-700"><TextInput label={label} value={value} onChange={onChange} /><p className="mt-2 text-xs text-slate-500">{hint}</p><label className="mt-3 inline-flex cursor-pointer rounded-xl border px-4 py-2 text-sm font-bold dark:border-slate-700"><input type="file" accept="image/*" className="sr-only" onChange={event => onUpload(field, event.target.files?.[0])} />{uploading === field ? 'Загружаем…' : 'Загрузить файл'}</label>{value && <div className="mt-3 flex max-h-64 items-center justify-center rounded-xl bg-slate-100 p-2 dark:bg-slate-800"><img src={value} className="max-h-60 w-full object-contain" alt="Предпросмотр" /></div>}</div>; }
