import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';
import type { Lesson } from '../../types';
import { getLessons, saveLesson, uploadImage } from '../../lib/contentService';

const schema = z.object({ titleRu: z.string().min(3), titleUz: z.string().min(3), descriptionRu: z.string().min(5), descriptionUz: z.string().min(5), youtubeUrl: z.string().url(), image: z.string().url(), level: z.enum(['A1', 'A2', 'B1', 'B2', 'C1']), tags: z.string() });
type Values = z.infer<typeof schema>;

export default function LessonFormPage() {
  const { id } = useParams(); const nav = useNavigate(); const [loading, setLoading] = useState(Boolean(id)); const [contentRu, setContentRu] = useState(''); const [contentUz, setContentUz] = useState(''); const [uploading, setUploading] = useState(false);
  const { register, handleSubmit, reset, setValue, watch, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { level: 'A1' } });
  useEffect(() => { if (id) getLessons().then(items => { const lesson = items.find(x => x.id === id); if (lesson) { reset({ titleRu: lesson.title.ru, titleUz: lesson.title.uz, descriptionRu: lesson.description.ru, descriptionUz: lesson.description.uz, youtubeUrl: lesson.youtubeUrl, image: lesson.image, level: lesson.level, tags: lesson.tags.join(', ') }); setContentRu(lesson.content?.ru || ''); setContentUz(lesson.content?.uz || ''); } setLoading(false); }); }, [id, reset]);
  const upload = async (file?: File) => { if (!file) return; setUploading(true); try { setValue('image', await uploadImage(file, 'lesson-images')); } finally { setUploading(false); } };
  const submit = async (v: Values) => { const item: Lesson = { id: id || crypto.randomUUID(), title: { ru: v.titleRu, uz: v.titleUz }, description: { ru: v.descriptionRu, uz: v.descriptionUz }, content: { ru: contentRu, uz: contentUz }, youtubeUrl: v.youtubeUrl, image: v.image, level: v.level, tags: v.tags.split(',').map(x => x.trim()).filter(Boolean), materials: [], views: 0, createdAt: new Date().toISOString() }; await saveLesson(item); nav('/admin'); };
  if (loading) return <div className="p-10">Loading…</div>;
  return <section className="mx-auto max-w-3xl px-4 py-10"><h1 className="text-3xl font-black">{id ? 'Редактировать урок' : 'Новый урок'}</h1><p className="mt-2 text-sm text-slate-500">Обложка загружается в Firebase Storage. Поддерживается длинный форматированный текст на двух языках.</p><form onSubmit={handleSubmit(submit)} className="mt-6 grid gap-4 rounded-2xl bg-white p-6 shadow-soft dark:bg-slate-900"><Input label="Название (RU)" error={errors.titleRu?.message} {...register('titleRu')}/><Input label="Sarlavha (UZ)" error={errors.titleUz?.message} {...register('titleUz')}/><Input label="Короткое описание (RU)" error={errors.descriptionRu?.message} {...register('descriptionRu')}/><Input label="Qisqa tavsif (UZ)" error={errors.descriptionUz?.message} {...register('descriptionUz')}/><label>Полный текст урока (RU)<ReactQuill theme="snow" value={contentRu} onChange={setContentRu}/></label><label>To‘liq dars matni (UZ)<ReactQuill theme="snow" value={contentUz} onChange={setContentUz}/></label><Input label="YouTube URL" error={errors.youtubeUrl?.message} {...register('youtubeUrl')}/><Input label="Image URL" error={errors.image?.message} {...register('image')}/><label className="text-sm font-semibold">Загрузить картинку<input type="file" accept="image/*" className="mt-1 block" onChange={e => upload(e.target.files?.[0])}/></label>{watch('image') && <img src={watch('image')} className="h-36 w-56 rounded-xl object-cover" alt="Предпросмотр"/>}<label>Уровень<select className="mt-1 w-full rounded-xl border bg-transparent p-3 dark:border-slate-700" {...register('level')}><option>A1</option><option>A2</option><option>B1</option><option>B2</option><option>C1</option></select></label><Input label="Теги (через запятую)" {...register('tags')}/><button disabled={isSubmitting || uploading} className="rounded-xl bg-brand-600 py-3 font-bold text-white">{uploading ? 'Загрузка…' : 'Сохранить'}</button></form></section>;
}
const Input = ({ label, error, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) => <label className="text-sm font-semibold">{label}<input className="mt-1 w-full rounded-xl border bg-transparent p-3 dark:border-slate-700" {...props}/>{error && <span className="text-xs text-rose-500">{error}</span>}</label>;
