import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm, type UseFormRegister } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';
import type { Lesson, Level } from '../../types';
import { getLessons, saveLesson, uploadImage } from '../../lib/contentService';
import { splitTags, tagsFor } from '../../lib/tags';

const urlOrEmpty = z.string().trim().refine(value => !value || z.string().url().safeParse(value).success, 'Введите корректную ссылку');
const schema = z.object({ titleRu: z.string().trim().min(3, 'Минимум 3 символа'), titleUz: z.string().trim().min(3, 'Kamida 3 ta belgi'), descriptionRu: z.string().trim().min(5, 'Минимум 5 символов'), descriptionUz: z.string().trim().min(5, 'Kamida 5 ta belgi'), youtubeUrl: z.string().trim().url('Введите ссылку YouTube'), image: urlOrEmpty, detailImage: urlOrEmpty, level: z.enum(['A1', 'A2', 'B1', 'B2', 'C1']), tagsRu: z.string(), tagsUz: z.string() });
type Values = z.infer<typeof schema>;
const levels: Level[] = ['A1', 'A2', 'B1', 'B2', 'C1'];
const quillModules = { toolbar: [['bold', 'italic', 'underline', 'strike'], [{ header: [1, 2, 3, false] }], [{ size: ['small', false, 'large', 'huge'] }], [{ list: 'ordered' }, { list: 'bullet' }], [{ align: [] }], ['link', 'image'], ['clean']] };

export default function LessonFormPage() {
  const { id } = useParams(); const nav = useNavigate(); const [loading, setLoading] = useState(Boolean(id)); const [contentRu, setContentRu] = useState(''); const [contentUz, setContentUz] = useState(''); const [uploading, setUploading] = useState<'image' | 'detailImage' | ''>(''); const [saveError, setSaveError] = useState('');
  const { register, handleSubmit, reset, setValue, watch, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { level: 'A1', image: '', detailImage: '', tagsRu: '', tagsUz: '' } });
  useEffect(() => { if (!id) return; getLessons().then(items => { const lesson = items.find(item => item.id === id); if (!lesson) { setSaveError('Урок не найден.'); return; } reset({ titleRu: lesson.title.ru, titleUz: lesson.title.uz, descriptionRu: lesson.description.ru, descriptionUz: lesson.description.uz, youtubeUrl: lesson.youtubeUrl, image: lesson.image, detailImage: lesson.detailImage || '', level: lesson.level, tagsRu: tagsFor(lesson.tags, 'ru').join(', '), tagsUz: tagsFor(lesson.tags, 'uz').join(', ') }); setContentRu(lesson.content?.ru || ''); setContentUz(lesson.content?.uz || ''); }).catch(() => setSaveError('Не удалось загрузить урок.')).finally(() => setLoading(false)); }, [id, reset]);
  const upload = async (field: 'image' | 'detailImage', file?: File) => { if (!file) return; try { setUploading(field); setSaveError(''); const url = await uploadImage(file, 'lesson-images'); setValue(field, url, { shouldDirty: true, shouldValidate: true }); } catch (error) { setSaveError(error instanceof Error ? error.message : 'Не удалось загрузить изображение.'); } finally { setUploading(''); } };
  const submit = async (values: Values) => { if (!values.image) { setSaveError('Добавьте обложку: вставьте URL или загрузите файл.'); return; } try { setSaveError(''); const item: Lesson = { id: id || crypto.randomUUID(), title: { ru: values.titleRu, uz: values.titleUz }, description: { ru: values.descriptionRu, uz: values.descriptionUz }, content: { ru: contentRu, uz: contentUz }, youtubeUrl: values.youtubeUrl, image: values.image, ...(values.detailImage ? { detailImage: values.detailImage } : {}), level: values.level, tags: { ru: splitTags(values.tagsRu), uz: splitTags(values.tagsUz) }, materials: [], views: 0, createdAt: new Date().toISOString() }; await saveLesson(item); nav('/admin'); } catch (error) { setSaveError(error instanceof Error ? error.message : 'Не удалось сохранить урок.'); } };
  if (loading) return <div className="p-10">Loading…</div>;
  return <section className="mx-auto max-w-3xl px-4 py-10"><h1 className="text-3xl font-black">{id ? 'Редактировать урок' : 'Новый урок'}</h1><p className="mt-2 text-sm text-slate-500">Обложка показывается в карточке. Фото внутри урока — отдельное и необязательное.</p><form noValidate onSubmit={handleSubmit(submit)} className="mt-6 grid min-w-0 gap-5 rounded-2xl bg-white p-6 shadow-soft dark:bg-slate-900"><Input label="Название (RU)" error={errors.titleRu?.message} {...register('titleRu')} /><Input label="Sarlavha (UZ)" error={errors.titleUz?.message} {...register('titleUz')} /><Input label="Короткое описание (RU)" error={errors.descriptionRu?.message} {...register('descriptionRu')} /><Input label="Qisqa tavsif (UZ)" error={errors.descriptionUz?.message} {...register('descriptionUz')} /><Editor label="Полный текст урока (RU)" value={contentRu} onChange={setContentRu} /><Editor label="To‘liq dars matni (UZ)" value={contentUz} onChange={setContentUz} /><Input label="YouTube URL" error={errors.youtubeUrl?.message} {...register('youtubeUrl')} /><ImageField label="Обложка для карточки" hint="URL или загрузка файла — достаточно одного варианта." field="image" value={watch('image')} error={errors.image?.message} uploading={uploading} register={register} onUpload={upload} /><ImageField label="Фото внутри урока (необязательно)" hint="Если оставить пустым, внутри будет только видео и текст." field="detailImage" value={watch('detailImage')} error={errors.detailImage?.message} uploading={uploading} register={register} onUpload={upload} /><div><p className="text-sm font-semibold">Уровень</p><div className="mt-2 grid grid-cols-5 gap-2">{levels.map(level => <button type="button" key={level} onClick={() => setValue('level', level, { shouldValidate: true })} className={'rounded-xl border py-3 font-bold transition ' + (watch('level') === level ? 'border-brand-600 bg-brand-600 text-white shadow-soft' : 'border-slate-200 hover:border-brand-400 dark:border-slate-700')}>{level}</button>)}</div></div><Input label="Теги (RU, через запятую)" placeholder="Грамматика, Времена" {...register('tagsRu')} /><Input label="Teglar (UZ, vergul orqali)" placeholder="Grammatika, Zamonlar" {...register('tagsUz')} />{saveError && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{saveError}</p>}<button disabled={isSubmitting || Boolean(uploading)} className="rounded-xl bg-brand-600 py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{uploading ? 'Загрузка…' : isSubmitting ? 'Сохранение…' : 'Сохранить урок'}</button></form></section>;
}

function Editor({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div className="min-w-0"><p className="mb-1 text-sm font-semibold">{label}</p><ReactQuill theme="snow" modules={quillModules} value={value} onChange={onChange} /></div>; }
function ImageField({ label, hint, field, value, error, uploading, register, onUpload }: { label: string; hint: string; field: 'image' | 'detailImage'; value: string; error?: string; uploading: string; register: UseFormRegister<Values>; onUpload: (field: 'image' | 'detailImage', file?: File) => void }) { return <div className="min-w-0 rounded-2xl border border-dashed border-slate-300 p-4 dark:border-slate-700"><Input label={label} error={error} placeholder="https://…" {...register(field)} /><p className="mt-2 text-xs text-slate-500">{hint}</p><label className="mt-3 inline-flex cursor-pointer rounded-xl border px-4 py-2 text-sm font-bold dark:border-slate-700"><input type="file" accept="image/*" className="sr-only" onChange={event => onUpload(field, event.target.files?.[0])} />{uploading === field ? 'Загружаем…' : 'Загрузить файл'}</label>{value && <div className="mt-3 flex max-h-64 items-center justify-center rounded-xl bg-slate-100 p-2 dark:bg-slate-800"><img src={value} className="max-h-60 w-full object-contain" alt="Предпросмотр" /></div>}</div>; }
const Input = ({ label, error, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) => <label className="min-w-0 text-sm font-semibold">{label}<input className="mt-1 min-w-0 w-full rounded-xl border bg-transparent p-3 break-all dark:border-slate-700" {...props} />{error && <span className="block text-xs text-rose-500">{error}</span>}</label>;
